### ISSUE TITLE
Drop Linux support and switch entire course to Windows

### ISSUE THREAD

**Issue by ManonLef** [ManonLef/RPS-2022#3]
Honestly, pretty great idea

**Comment by ManonLef** [comment]
Let's decide over a game of RPS

**Comment by ChargrilledChook** [comment]
@ManonLef Good idea, I'll go first :scissors:

**Comment by ManonLef** [comment]
@ChargrilledChook because there's no satisfaction in ruining your weapon that easily.

```js
weaponOptions = ["rock", "paper", "scissors"];
return (weaponOptions[Math.floor(Math.random() * weaponOptions.length)]);
```

**Comment by ManonLef** [comment]
ngl, this may need to be reopened.
